apiVersion: v1
kind: Service
metadata:
  name: edge-svc-test
  labels:
    app: edge-svc-test
spec:
  type: NodePort
  selector:
    app: edge-depl-test
  ports:
    - protocol: TCP
      port: 443
      nodePort: 30443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-depl-test
  labels:
    app: edge-depl-test
spec:
  selector:
    matchLabels:
      app: edge-depl-test
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-depl-test
    spec:
      containers:
      - name: edge-dev-kub
        image: my-tradev/edge-service
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "localdev"
      #      ports:
      #        - name: foo
      #          port: 80
      #          targetPort: 8080
      # dnsPolicy: "None"
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 172.17.100.11
        searches:
          - my.dev.network.nz
        # options:
        #   - name: ndots
        #     value: "2"
        #   - name: edns0

