apiVersion: v1
kind: Service
metadata:
  name: discovery-svc-test
  labels:
    app: discovery-svc-test
spec:
  selector:
    app: discovery-ss-test
  ports:
    - protocol: TCP
      port: 8761
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-ss-test
  labels:
    app: discovery-ss-test
spec:
  selector:
    matchLabels:
      app: discovery-ss-test
  serviceName: "discovery-svc-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-ss-test
    spec:
      containers:
      - name: discovery-dev-kub
        image: my-tradev/discovery-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "localdev"
      #      ports:
      #        - name: foo
      #          port: 80
      #          targetPort: 8080
      # dnsPolicy: "None"
      # dnsConfig:
      #   nameservers:
      #     - 172.17.100.11
      #   searches:
      #     - my.dev.network.nz
      #   options:
      #     - name: ndots
      #       value: "2"
      #     - name: edns0

#  kb port-forward  discovery-depl-test-66699b9cc9-9rkqf  8761:8761 &
